apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jtrac-app
  name: jtrac-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jtrac-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jtrac-app
    spec:
      containers:
      - image: rambpm/jtrac:v1.2
        name: jtrac
        ports:
        - containerPort: 8080
        env:
        - name: database_driver
          value: "com.mysql.jdbc.Driver"
        - name: database_url
          value: "jdbc:mysql://mysql:3306/jtrac"
        - name: database_username
          value: "root"
        - name: database_password
          value: "password@1"
        - name: hibernate_dialect
          value: "org.hibernate.dialect.MySQLDialect"
        - name: hibernate_show_sql
          value: "false"
