apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jtrac-app
  name: jtrac-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jtrac-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jtrac-app
    spec:
      containers:
      - image: rambpm/jtrac:v1.3
        name: jtrac
        ports:
        - containerPort: 8080
        env:
        - name: database_driver
          valueFrom:
           configMapKeyRef:
            name: jtrac-config
            key: database_driver

        - name: database_url
          valueFrom:
           configMapKeyRef:
            name: jtrac-config
            key: database_url

        - name: database_username
          valueFrom:
           secretKeyRef:
            name: db-secret
            key: database_username

        - name: database_password
          valueFrom:
           secretKeyRef:
            name: db-secret
            key: database_password

        - name: hibernate_dialect
          valueFrom:
           configMapKeyRef:
            name: jtrac-config
            key: hibernate_dialect
 
        - name: hibernate_show_sql
          valueFrom:
           configMapKeyRef:
            name: jtrac-config
            key: hibernate_show_sql
           
